version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_PASSWORD: "3306:3306"  # Исправлено на "your_password"
      MYSQL_HOST: "localhost"
      MYSQL_USER: krago  # исправлено с MYSQLL_USER на MYSQL_USER
      
      MYSQL_ROOT_PASSWORD: "0089"
      MYSQL_DATABASE: BudgetController
      
    command: --default-authentication-plugin=mysql_native_password
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
